/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Pool;

import javafx.application.Application;
import javafx.stage.Stage;

import java.io.IOException;
import javafx.event.EventHandler;
import javafx.scene.control.Button;
import javafx.util.Duration;

public class TestClassM extends Application {
    @Override
    public void start(Stage stage) throws IOException {
        Sound.initiateSound();
        //create scenes
        SceneWelcome sceneWelcome = new SceneWelcome();
        ScenePlayGrass scenePlayGrass = new ScenePlayGrass();
        ScenePlayNormal scenePlayNormal = new ScenePlayNormal();
        ScenePlayIce scenePlayIce = new ScenePlayIce();
        

        stage.setHeight(780);
        stage.setWidth(1350);
        stage.setResizable(false);

        stage.setScene(sceneWelcome.getScene());
        stage.show();
        
        
        
        
        
        
        
        //action handlers for repetitive actions
//GO TO SCENES
        EventHandler gotToNormal = e->{
            stage.setScene(scenePlayNormal.getScene());
            GameStatus.gameState = 0;
        };
        EventHandler gotToGrass = e->{
            stage.setScene(scenePlayGrass.getScene());
            GameStatus.gameState = 1;
        };
        EventHandler gotToIce = e->{
            stage.setScene(scenePlayIce.getScene());
            GameStatus.gameState = 2;
        };
//BUTTON ACTIONS
        EventHandler btnOnMouseEntered = e->{
            Button target = (Button)e.getTarget();
            target.setScaleX(1.5);
            target.setScaleY(1.5);
            Sound.btnSound.stop();
            Sound.btnSound.play();
        };
        EventHandler btnOnMouseExited = e->{
            Button target = (Button)e.getTarget();
            target.setScaleX(1);
            target.setScaleY(1);
            Sound.btnSound.stop();
            Sound.btnSound.play();
        };
        
        
//SCENE_WELCOME
        //Button Events
        sceneWelcome.normalBtn.setOnAction(gotToNormal);
        sceneWelcome.grassBtn.setOnAction(gotToGrass);
        sceneWelcome.iceBtn.setOnAction(gotToIce);
        
        sceneWelcome.normalBtn.setOnMouseEntered(btnOnMouseEntered);
        sceneWelcome.normalBtn.setOnMouseExited(btnOnMouseExited);
        sceneWelcome.grassBtn.setOnMouseEntered(btnOnMouseEntered);
        sceneWelcome.grassBtn.setOnMouseExited(btnOnMouseExited);
        sceneWelcome.iceBtn.setOnMouseEntered(btnOnMouseEntered);
        sceneWelcome.iceBtn.setOnMouseExited(btnOnMouseExited);
        
//SCENE_PLAY
        
    }
    public static void main(String[] args) {
        Application.launch();
    }
}
