/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Pool;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseButton;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class TestClass extends Application{

    public static void main(String[] args) {
        Application.launch();
    }

    @Override
    public void start(Stage ps) throws Exception {
        
        //CustomAnimation dino = new CustomAnimation("gaming_DinoSprites_walk",-5);
        Pane pane = new Pane();
        
       // pane.getChildren().add(dino);
        Scene sc = new Scene(pane,200,200);
        /*
        sc.setOnMouseClicked(e->{
            if(e.getButton()== MouseButton.PRIMARY){dino.nextFrame();}
            else if(e.getButton()== MouseButton.SECONDARY){dino.previousFrame();}
        });
        */
        Vector v = new Vector(-4,4);
        System.out.println(Math.toDegrees(v.getAngle()));
        
        ps.setTitle("testScene");
        ps.setScene(sc);
        ps.show();

    }
}
